---
- name: Configure MacBook with Ansible
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: install brew packages
      become: false
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - colima
        - kubectl
        - helm
        - kubectx
        - argocd
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - zsh-completions
        - zsh-history-substring-search
        - flux
        - azure-cli
    - name: install casks
      become: false
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - iterm2
        - amethyst
        - discord
        - expressvpn
        - flutter
        - spotify
        - vlc
        - datagrip
        - rider
        - cursor
  - name: isntall taps
    community.general.homebrew_tap:
      name: "{{ item }}"
      state: present
    loop:
      - ksd

  - name: Ensure colima is configured
    shell: colima start --profile rosetta --cpu 4 --memory 8 --disk 100 --arch aarch64 --vm-type=vz --vz-rosetta --mount-type virtiofs

# setup colima if it is not already installed properly - something like this as default mnachine;  colima start --profile rosetta --cpu 4 --memory 7 --disk 60 --arch aarch64 --vm-type=vz --vz-rosetta --mount-type virtiofs
# - name: Ensure colima is installed
#   homebrew_cask:
#     name: colima
#     state: present

