---
- name: Configure MacBook with Ansible
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Homebrew casks are installed
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - iterm2
